_BASE_: mask2former_R50_bs2_100ep.yaml
MODEL:
  WEIGHTS: "models/edited_swin_s.pkl"
  BACKBONE:
    NAME: "D2SwinTransformer"
  MASK_FORMER:
    SKIPS: [0,1,2,3,4,5,6,7,8]
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: output/swin_freeze_bb_4_lr_00001_100_dist_skips_all