_BASE_: mask2former_R50_bs2_100ep.yaml
MODEL:
  BACKBONE:
    NAME: "build_mnv2_backbone"
    FREEZE_AT: 12
  WEIGHTS: "models/mobilenet_v2-7ebf99e0.pth"
  MASK_FORMER:
    DEC_LAYERS: 4
    DEEP_SUPERVISION: True
SOLVER:
  IMS_PER_BATCH: 3
  BASE_LR: 0.00001
  STEPS: (39187, 45485)
  MAX_ITER: 46900
OUTPUT_DIR: output/mobile_frozen_12_00001_deep