_BASE_: mask2former_R50_bs2_100ep.yaml
MODEL:
  MASK_FORMER:
    DEEP_SUPERVISION: True
    DEC_LAYERS: 4
SOLVER:
  IMS_PER_BATCH: 3
  BASE_LR: 0.0001
  STEPS: (58780, 68227)
  MAX_ITER: 70350
OUTPUT_DIR: output/R50_deep_supervision_compact_0001